class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start5'
        self.MirrorCommand = 'mirror5'
        self.UnzipMirrorCommand = 'unzipmirror5'
        self.TarMirrorCommand = 'tarmirror5'
        self.CancelMirror = 'cancel5'
        self.CancelAllCommand = 'cancelall5'
        self.ListCommand = 'look5'
        self.StatusCommand = 'status5'
        self.AuthorizeCommand = 'auth5'
        self.UnAuthorizeCommand = 'unauth5'
        self.AuthListCommand = 'users5'
        self.PingCommand = 'ping5'
        self.RestartCommand = 'reboot5'
        self.StatsCommand = 'stats5'
        self.HelpCommand = 'help5'
        self.LogCommand = 'log5'
        self.SpeedCommand = 'speedtest5'
        self.CloneCommand = 'clone5'
        self.WatchCommand = 'watch5'
        self.TarWatchCommand = 'tarwatch5'
        self.DeleteCommand = 'dx5'
        self.UsageCommand = 'usage5'
        self.RepoCommand = 'repo5'

BotCommands = _BotCommands()
